events {
    worker_connections 1024;
}

http {
    upstream auth {
        server auth-service:8080;
    }
    upstream orders {
     server order-service:8080;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth/api/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            auth_request /_auth_check;
            auth_request_set $auth_status $upstream_status;

            proxy_pass http://orders/api/orders/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location = /_auth_check {
            internal;
            
            proxy_pass http://auth/api/auth/verify;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header Authorization $http_authorization;
        }

        error_page 401 = @unauthorized;
        location @unauthorized {
            return 401 '{"error": "Unauthorized", "message": "Invalid or missing token"}';
            default_type application/json;
        }
    }
}